### PR TITLE
Allow user to add annotation's flag.

### PR DESCRIPTION
**Pull request by chunyenHuang**
1. Add writeIntegerValue to dictionaryContext. 
1. Allow users to set annotation's flag.

### CODE REVIEW

**Comment by galkahana** [comment]
Cheers. How about completing this to a full number support? Javascript doesnt make type difference between integer and floats, and id rather have no errors here.

**Comment by chunyenHuang** [comment]
Sure thing, I will commit it soon.

**Comment by galkahana** [comment]
writeNumberValue is probably best

**Comment by galkahana** [comment]
you can borrow from the matching objectscontextmethod - https://github.com/galkahana/HummusJS/blob/master/src/ObjectsContextDriver.cpp#L168

**Pull request merged**
