### PR TITLE
add initial typescript typings

### PR DESCRIPTION
**Pull request by moshensky**
Most of the credit for the typings should go to @jsgoupil. I have slightly enhanced typings based on my needs more then a year ago.
Relevant issue: https://github.com/galkahana/HummusJS/issues/107

### CODE REVIEW

**Comment by jsgoupil** [comment]
Thanks for the credit! I'm happy it helped on the contribution.

**Comment by galkahana** [comment]
thanks @moshensky and @jsgoupi.
Tests failures are not on account of your work. rather it's electron-mocha upgrade that screwed things up.
Let's do this :).

**Comment by galkahana** [comment]
published as 1.0.97

**Comment by moshensky** [comment]
@galkahana I have installed 1.0.97, but the changes are not reflected. `package.json` is without the needed prop and the `.d.ts` file is missing too.

**Comment by galkahana** [comment]
probably cause it's not in the package.json files entry

**Comment by galkahana** [comment]
the types prop is in there, it's the file that's not. so i'll prep another build with the corrected files entry

**Comment by galkahana** [comment]
ok. 1.0.98 is now published. seems like the types connectivity is working well. thank you.

**Comment by galkahana** [comment]
All thanks goes to these guys ;).

Must say that now that i'm seeing the result it is quite motivating. it's really helpful. going forward i'll try to add to it.

**Comment by tolotrasamuel** [comment]
I am using  "hummus": "^1.0.105" from npm install --save hummus but I do not see the type definition

**Pull request merged**
