### PR TITLE
Add electron 5 pre-builts

### PR DESCRIPTION
**Pull request by rbeeger**
Tries to add electron 5 pre builts after https://github.com/galkahana/HummusJS/pull/374 was merged.

Also tries to add electron 4 pre-builts, but for me it would be just fine if it only works for electron 5, but it might also work for electron 4. Let's see.

### CODE REVIEW

**Comment by rbeeger** [comment]
That doesn't work https://travis-ci.org/galkahana/HummusJS/jobs/527328672

**Comment by galkahana** [comment]
i reckon it's a matter of choosing the right version of electron vs. the right version of node.  lemme run some tests.

**Comment by galkahana** [comment]
an update here. well actually the dlls are compiled well. the problem is rather with the testing part, which run `mocha`. This will attempt running the tests with regular node which has different chrome run times, which is the cause for the error.  To correct this, one only has to run with `electron mocha` instead, something which is being done in the PC script for creating binaries. Adding electron mocha solves the problem for OSx. Now i'm fighting with Linux which runs headless and has a few issues with electron mocha. while there's a recipe on how to run `electron mocha` on linux, there's some exceptions being thrown and im trying to figure them out.

**Comment by galkahana** [comment]
nother update. so fighting with linux wasnt successful. while there's explanations on how to run electron mocha on headless linux the tests keep on crashing. one could try and debug this...but its a bit of an effort here, and i tried to run travis or just a damn headless linux locally for faster round trips...but that failed when i tried to run electron mocha. all too much for me at this point.

so...update the travis script to build electron binaries for mac for the new versions that needed electron mocha, but let the earlier version which matched regular node as is. so now you'll get mac electron binaries.

to clarify, the problem all along was not with the creation of binaries, which is fine, it's with testing them. now one could say - drop the testing for this....but given that these go outside to the world, i'd rather not have binaries, then send something without some sanity testing. wont tell you what to do on your private repo ;)

**Comment by larssvensby** [comment]
Any progress on this?

**Comment by d4kris** [comment]
For anyone else who is waiting for this, we managed to build locally for electron 5 by adding dist-url:  `npm rebuild hummus --build-from-source=hummus --target=5.0.2 --runtime=electron --dist-url=https://atom.io/download/electron"`

**Pull request merged**
