### PR TITLE
Add electron to builds

### PR DESCRIPTION
**Pull request by hhaidar**
I tried my best.

Ref #294

### CODE REVIEW

**Comment by galkahana** [comment]
k. that doesn't really work.
i mean compiling seems to happen, but seems like with publishing it doesn't work.
try to figure out how node-pre-gyp/travis should work with electron and let's try again

**Comment by galkahana** [comment]
this build is for reference:
https://travis-ci.org/galkahana/HummusJS/builds/417938173

when i tried to use it with publish binary

**Comment by hhaidar** [comment]
I think we can accomplish that by setting a few env vars:

```
- if [[ $ELECTRON_VERSION ]]; then
  export npm_config_target=$ELECTRON_VERSION;
  export npm_config_target_arch=x64;
  export npm_config_disturl=https://atom.io/download/electron;
  export npm_config_runtime=electron;
  fi
```
I'm trying that out locally.

**Comment by hhaidar** [comment]
This should do it: #316

**Comment by galkahana** [comment]
k. binaries are up. wanna give it a spin?

**Comment by hhaidar** [comment]
👍 👍 👍

**Pull request merged**
