### PR TITLE
Added support for image stream on PDFWriter::getImageDimensions

### PR DESCRIPTION
**Pull request by willy2dg**
PR to solve #354 

Adds implementation to accept a stream as getImageDimensions parameter and includes required internal methods to acomplish it.

JPEGImageHandler::RetrieveImageInformation using stream as parameter
DocumentContext::GetImageType using stream as parameter

### CODE REVIEW

**Comment by willy2dg** [comment]
Hi @galkahana , seems Travis failed to prepare enviroment for NodeJS 11, but the issue is not related to the PR. Is there some way i can fix it ? Or i am forced to commit something to run Travis again ?

**Comment by goatandsheep** [comment]
The 502 Bad Gateway seems to be an [unresolved issue on the Travis end](https://travis-ci.community/t/502-bad-gateway-when-updating-from-custom-apt-repo/3916)

**Comment by goatandsheep** [comment]
@willy2dg can you please expand to Travis-CI on [the related ticket](https://support.travis-ci.com/hc/en-us/requests/11182)

**Comment by willy2dg** [comment]
@goatandsheep , the ticket link is broken. Anyway, the error seems to have happened when downloading a dependency for the test environment, server responded with 502, so that an "empty commit" would probably pass the tests successfully.

**Comment by goatandsheep** [comment]
@willy2dg [I have verified your fork builds successfully](https://travis-ci.com/goatandsheep/HummusJS/builds/128554222). I recommend you push an [empty commit](https://coderwall.com/p/vkdekq/git-commit-allow-empty) just to get the green checkbox. @galkahana please take a look when possible.

**Comment by goatandsheep** [comment]
@willy2dg I've heard pindrop silence from @galkahana :(

**Comment by galkahana** [comment]
published as 106

**Pull request merged**
