### PR TITLE
Support musl based binaries

### PR DESCRIPTION
**Pull request by junamai2000**
Can you support musl libc? The current uploaded libraries is based on glibc. So I can not use your fantastic library on alpine.

#230 
#111 

I am not sure how to make musl libc based binary on travisci. If you know, please help me.

### CODE REVIEW

**Comment by marcato15** [comment]
@galkahana Any update on merging this in? Would love to use Hummus on alpine.

**Comment by galkahana** [comment]
Guys, this is like beyond me. Im a humble programmer not initiated in such terms as glibc or musl. So go get yr os expert and lets make this happen.

**Comment by galkahana** [comment]
ok. i think i got it, both the flag and the travis part, somebody wants to give this a try?

**Comment by marcato15** [comment]
Thanks! Will take a look this week and report back if there are any issues.

**Pull request closed without merging**
